### ISSUE TITLE
Translation welcome?

### ISSUE THREAD

**Issue by c0pie** [harborsiem/ELEMNTViewer#1]
Hi
Is it possible or desired to translate the program into other languages, e.g. german?

**Comment by harborsiem** [comment]
I think translation is possible with some effort. But my time to this is very restricted.

**Comment by c0pie** [comment]
I don't know how complicated it is to implement this. If you say 'the effort exceeds the benefit', than it's okay for me.
But if it's 'just' a few lines of code that need to be inserted for the language strings or something like this, then i will do my best and try to translate this in german.

**Comment by harborsiem** [comment]
- The complicated part for this issue are the objects like Session, Laps, Gears, Session Extras, Heartrate Zones, Power Zones in the PropertyGrid dialog. For all objects is a redesign necessary. But for this redesign there is no standard available. I don't know how complicated this can be.
- The redesign for the Ribbon menus will also take some time.
- We also have to do a list with all language independent strings for translation. After translation we had to put them in language specific resource files.

When I look at all these things to do, then I have to say that it will be a big effort.

**Comment by c0pie** [comment]
Thank you for your statement.
Okay, it sounds more complicated than 'just a few lines of code'.

**Comment by tajbender** [comment]
> * The complicated part for this issue are the objects like Session, Laps, Gears, Session Extras, Heartrate Zones, Power Zones in the PropertyGrid dialog. For all objects is a redesign necessary. But for this redesign there is no standard available. I don't know how complicated this can be.
> * The redesign for the Ribbon menus will also take some time.
> * We also have to do a list with all language independent strings for translation. After translation we had to put them in language specific resource files.
> 
> When I look at all these things to do, then I have to say that it will be a big effort.

...Hi, @harborsiem 

it's been a long time...
Manic Depression again.

I can look at this. Please remind me, if I should forget about it.

thx

**Comment by harborsiem** [comment]
I have done a pre release version 2.4.2. With this version it is possible to test a german version.

**Comment by c0pie** [comment]
Thanks for the update, but ...
there is no translated string/menu option (on my Windows 10 Pro machine)
I've first updated from 2.41, the only visible difference is the "settings" entry under "Datei"; no translation. Okay, then i deleted the old version and installed the new (2.42). But again, no german translation. Thirdly i deleted the user entries under "C:\Users\xxx\AppData\Local\ELEMNTViewer" after the deinstallation and reinstalled again, but no change even now.
Is the problem on my side?
The menu option "settings" is empty:

![settings_menu](https://github.com/harborsiem/ELEMNTViewer/assets/118180634/1b1e8ad8-d2e7-40c2-9029-c39622d35e6f)

**Comment by harborsiem** [comment]
![Localize](https://github.com/harborsiem/ELEMNTViewer/assets/28147549/b36c09ab-5ac1-49a1-96b1-491799b3651d)
To activate the german translation you have to press
1. Settings toggle button (you get a new tab called "Settings")
2. Go to the Settings Tab
3. Click to the Localize checkbox
4. Save it to the settings file
5. Close and restart the ElemntViewer (now you should get german text if you have a german Windows version)

**Comment by c0pie** [comment]
Thank you for the explanation, it works.
Would you like to suggest changes for some terms?

**Comment by harborsiem** [comment]
There is a new release version 2.5. In this version I fixed some terms. But you can suggest changes.

**Comment by c0pie** [comment]
Thanks for the update.

Imho the term "Climbing" sounds better "Anstieg" in german than "Klettern".
And the name "Tempo" (1.) is okay, but then I'd change the name of the menu item "Tempo" (2.) in "Geschwindigkeit". It shows what it is: the driven speed on the tour

![Einstellungen](https://github.com/harborsiem/ELEMNTViewer/assets/118180634/770c271e-94bb-4f73-b740-5e7e52e2ed8d)

**Comment by harborsiem** [comment]
@c0pie Thanks for translation. In the next version I will take the term "Anstieg" instead "Klettern". It sounds better.
But I don't change the term "Tempo". I have found [this definition](https://www.physik-und-schule.de/studgloss/sg002.html). Also Wahoo used mostly the term "Tempo" in the app.
The next version will come soon (Maybe I wait until new version of the map control)
